[package]
name = "svgbob"
version = "0.6.2"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
edition = "2018"
description = "Transform your ascii diagrams into happy little SVG"
repository = "https://github.com/ivanceras/svgbob"
documentation = "https://docs.rs/svgbob"
keywords = ["ascii","plain","text", "svg", "bob"]
license = "Apache-2.0"

[dependencies]
nalgebra = "0.30.1"
parry2d = "0.8.0"
lazy_static = "1.3.0"
sauron = { version = "0.43.11", default-features = false}
#sauron = { version = "0.43.10", default-features = false, path = "../../../sauron"}
unicode-width = "0.1.9"
itertools = "0.10.3"
pom = { version = "3.2.0" }
log = "0.4.14"



[features]
# This affects the rendering of text nodes
# if the svg is rendered statically, characters such as '<' needed to be escaped
# while if it is rendered in the dom, no escaping is needed.
with-dom = ["sauron/with-dom"]

